export { createAppClient } from './client.js'
export {
  sendPhoneOtp,
  sendEmailOtp,
  sendPhoneChangeOtp,
  verifyPhoneOtp,
  verifyEmailOtp,
  verifyPhoneChangeOtp,
  upsertCurrentUserProfile,
  verifyOtpAndSyncProfile,
  completeSignupProfile,
  fetchCustomerSettings,
  updateCustomerSettings,
  logout,
} from './auth.js'
export {
  buildEsewaPaymentRequest,
  buildEsewaStatusUrl,
  createEsewaTransactionUuid,
  decodeEsewaResponseData,
  generateEsewaSignature,
  getEsewaConfig,
  mapEsewaStatusToPaymentStatus,
  verifyEsewaResponseSignature,
} from './esewa.js'
export {
  fetchActiveRestaurants,
  fetchActiveMenu,
  fetchAdminDashboard,
  fetchRestaurantFeed,
  fetchCustomerOrders,
  fetchOwnedRestaurant,
  fetchRestaurantDashboard,
  fetchRestaurantOrders,
  fetchRestaurantOrderDetails,
  fetchRestaurantMenuItems,
  fetchRestaurantOperatingSettings,
  getDefaultRestaurantOperatingHours,
  subscribeToRestaurantFeed,
  subscribeToRestaurantOrders,
  subscribeToCustomerOrders,
  updateRestaurantOrderStatus,
  submitRiderApplication,
  fetchRiderProfile,
  updateRiderAvailability,
  fetchRiderJobs,
  subscribeToRiderJobs,
  claimRiderJob,
  updateRiderLocation,
  updateRiderDeliveryStatus,
  updateRiderEta,
  updateRestaurantOperatingSettings,
  saveRestaurantMenuItem,
  deleteRestaurantMenuItem,
  submitRestaurantApplication,
  updateRestaurantProfile,
  verifyAdminRestaurantApplication,
  verifyAdminRiderApplication,
  setAdminProfileStatus,
  deleteAdminProfile,
  createOrder,
  createCheckoutOrder,
  updateOrderStatus,
  updateOrderPaymentStatus,
  submitContactForm,
  fetchContactSubmissions,
  markContactSubmissionRead,
  uploadAvatar,
  uploadRestaurantImage,
} from './queries.js'
