ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE food_places ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Profiles viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users insert own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Food places viewable by everyone" ON food_places FOR SELECT USING (true);
CREATE POLICY "Owners update their food place" ON food_places FOR UPDATE USING (auth.uid() = owner_id);
CREATE POLICY "Owners insert their food place" ON food_places FOR INSERT WITH CHECK (auth.uid() = owner_id);
CREATE POLICY "Menu items viewable by everyone" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Owners manage their menu" ON menu_items FOR ALL USING (EXISTS (SELECT 1 FROM food_places WHERE id = menu_items.food_place_id AND owner_id = auth.uid()));
CREATE POLICY "Customers view own orders" ON orders FOR SELECT USING (auth.uid() = customer_id);
CREATE POLICY "Customers create orders" ON orders FOR INSERT WITH CHECK (auth.uid() = customer_id);
CREATE POLICY "Restaurants manage their orders" ON orders FOR ALL USING (EXISTS (SELECT 1 FROM food_places WHERE id = orders.food_place_id AND owner_id = auth.uid()));
CREATE POLICY "Riders view ready or own orders" ON orders FOR SELECT USING (status = 'ready_for_pickup' OR rider_id = auth.uid());
CREATE POLICY "Riders update claimed orders" ON orders FOR UPDATE USING (rider_id = auth.uid() OR rider_id IS NULL);
CREATE POLICY "Order items viewable by participants" ON order_items FOR SELECT USING (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND (orders.customer_id = auth.uid() OR orders.rider_id = auth.uid() OR EXISTS (SELECT 1 FROM food_places WHERE id = orders.food_place_id AND owner_id = auth.uid()))));
CREATE POLICY "Customers insert order items" ON order_items FOR INSERT WITH CHECK (EXISTS (SELECT 1 FROM orders WHERE orders.id = order_items.order_id AND orders.customer_id = auth.uid()));
CREATE POLICY "Users manage own notifications" ON notifications FOR ALL USING (auth.uid() = user_id);
